spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/payment_db
      database: payment_db
      auto-index-creation: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: mongodb://localhost:27017/payment_db
    database-changelog-table: databasechangelog
    database-changelog-lock-table: databasechangeloglock
    mongodb:
      enabled: true
    drop-first: false
    contexts:
      - development

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.liquibase: INFO
    org.springframework.data.mongodb.core: DEBUG
    org.liquibase.ext.mongodb: DEBUG