spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      properties:
        spring.json.type.mapping: paymentEvent:com.example.paymentservice.event.PaymentEvent
        # Убраны избыточные настройки, оставлены только essentials

  liquibase:
    url: ${LIQUIBASE_URL:mongodb://mongodb:27017/payment_db}

logging:
  level:
    org.springframework.kafka: DEBUG