spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
      auto-index-creation: true

  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    change-log: ${LIQUIBASE_CHANGE_LOG}
    url: ${LIQUIBASE_URL}
    database-changelog-table: databasechangelog
    database-changelog-lock-table: databasechangeloglock
    mongodb:
      enabled: true
    drop-first: false
    contexts:
      - development

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentEvent:com.example.paymentservice.event.PaymentEvent
        spring.json.add.type.headers: true
        linger.ms: 0
        batch.size: 16384
        buffer.memory: 33554432
      retries: 3
      acks: all

server:
  port: 8084

logging:
  level:
    org.springframework: INFO
    org.liquibase: INFO
    org.springframework.data.mongodb.core: DEBUG
    org.liquibase.ext.mongodb: DEBUG
    com.example.paymentservice: DEBUG

# External API configuration
external:
  api:
    random-number:
      url: ${EXTERNAL_API_URL}
      timeout: 5000 # milliseconds