apiVersion: v1
kind: Secret
metadata:
  name: payment-mongodb-secret
  namespace: microservice-network
type: Opaque
data:
  mongo-initdb-database: cGF5bWVudF9kYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: zookeeper-secret
  namespace: microservice-network
type: Opaque
data:
  zookeeper-client-port: MjE4MQ==
  zookeeper-tick-time: MjAwMA==